### ISSUE TITLE
[BUG] Really annoying bug lets cadets get weapons.

### ISSUE THREAD

**Issue by CFWarfare** [DrewBokman/AOTG-Public-Issue-Board#12]
**Describe the bug**
Cadets/Civilians can get weapons using shiftlock on the ODM cabin.

**To Reproduce**
1. Go to the roof of the ODM cabin
2. Drop down to the sides, behind the cabin
3. Activate shiftlock and move your camera so that it goes inside the cabin
4. Click the boxes to get all the weapons.

**Expected behavior**
You get all the weapons.

**Screenshots**
Gyazo video: https://gyazo.com/55cfd53824b306995bbee00234b22e73

**Additional context**
It's really annoying to have to fight people who just do that for 'fun', Thanks.

**Comment by DrewBokman** [comment]
fixing rn

**Comment by DrewBokman** [comment]
Fixed

**Comment by CFWarfare** [comment]
Thanks!
