### ISSUE TITLE
a key to cancel a slash

### ISSUE THREAD

**Issue by j9cks** [DrewBokman/AOTG-Public-Issue-Board#15]
i think it would be good to add a keybind to cancel your slash if your blades are charged, it would prevent lots of random tk because people need to check their gas and have their blades charged etc. overall more realistic and helpful for everyone

**Comment by DrewBokman** [comment]
If i were to do this, what key would you suggest putting?

**Comment by Roderinian** [comment]
Clarify key

**Comment by DrewBokman** [comment]
A key/button on your keyboard..? What else would a "key" be in this context

**Comment by Roderinian** [comment]
Oh I am a idiot lol, I would say make it F since it is a easy button to click in a fast amount of time.

**Comment by DrewBokman** [comment]
I believe that might conflict with other keybinds but i will have to see.

**Comment by Roderinian** [comment]
For blade slashing I do not think F conflicts but if it dose then RIP, but I think it would only conflict if someone had there blades out while doing something else which they shouldn't

**Comment by DrewBokman** [comment]
Done, ready to be tested and merged with the main branch.
