### ISSUE TITLE
Cannon stuff

### ISSUE THREAD

**Issue by Roderinian** [DrewBokman/AOTG-Public-Issue-Board#16]
My feature request is related to the problem that a cannon shot takes 2 shots to kill a titan

I would like a cannon ball to one shot if hit in the nape or blind if hit in the head.

Alternatives could be that it takes a close shot to the nape (example the titan is hugging the wall) to kill the titan in one shot.

It would not make sense if a cannon ball could not one shot to the nape a titan.

**Comment by Roderinian** [comment]
Basically, make cannons blind if shot a titan in its head or kill in a one shot in the nape. This is because is a 100 MPH cannon ball can not one shot a titan nape but a thin metal blade can then it really makes no sense in lore :/

**Comment by Isushumi** [comment]
Cannons aren't even out, where did you get the idea that cannons 2 shot? We haven't even talked about how balancing them would work
