### ISSUE TITLE
[BUG] shooting yourself

### ISSUE THREAD

**Issue by Roderinian** [DrewBokman/AOTG-Public-Issue-Board#19]
When running / falling down / running and jumping and just moving while shooting in general it has a chance of shooting yourself which is a voidable thing but I suggest it get's fixed. 

**To Reproduce**
1. Go to a random place in AOT:G
2. Click on a flintlock or musket
3. Scroll down to equip musket or flintlock (happens more with flintlock)
4. Then just start running forwards with your gun pointed forwards and eventually it will kill yourself, sometimes it might take a bit but still it is a problem.

Expected behavior is for it to not shoot yourself yet shoot the person you are trying to shoot but still it dose shoot yourself sometimes.

**Screenshots**

**Additional context**
Please fix it, I do not know how you could but please do. it is a pretty big problem.

**Comment by DrewBokman** [comment]
fixed
