### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by warane** [DrewBokman/AOTG-Public-Issue-Board#24]
**Describe the bug**
After killing a titan or getting a kill assist (blind)
Kills/blinds didn't register into my character's kill count.
To be exact only the first one of each was registered.

**To Reproduce**
I've got no idea how to reproduce this, it happened during a PD, Im not testing bugs when there is a PD

**Expected behavior**
---------

**Screenshots**
I had 6 kills and 0 kill assist
https://gyazo.com/0c04dd414023e380e062888b40ae5418 - 1 Blind + Kill assist
https://gyazo.com/23971be003fab75a0556c0762902fba5 --- 1 Kill
https://gyazo.com/65d1098e8905148271b2174c88f4f345 --- 1 Blind + kill assist
https://gyazo.com/56f49fb8be59df0d3994300935b9d3f9 --- 1 Blind + kill assist
https://gyazo.com/adcb5a68310853c1b9bff6f817f8768a --- 1 kill (2 in total)
https://gyazo.com/dc7e132aaa7b9b8fedd7f4a01a806ca6 --- 1 Blind + kill assist
https://gyazo.com/31aca11f741aa4f8a62314f947e34453 --- 1 Blind + kill assist
https://gyazo.com/565717eaef7ec8fab0a0be0cc19647fa --- 1 Blind + kill assist
https://gyazo.com/5beb2d583b09130e4b9b29631628d6c2 -1 Blind + Kill assist
https://gyazo.com/b6e0263605de7241cbba9308fa8f3cb8 - 1 Blind + Kill assist
https://gyazo.com/c0fa6d3cc9d2f813b2cb676b3b6137ed -- 1 Blind + Kill assist 
https://gyazo.com/2a982f125c989e05d3a58628a1ba3d33 -- 1 Blind + kill assist 
https://gyazo.com/b25565d8096690f9fecbc4ddff5bed83 -- 1 Blind + kill assist (10-11 in total)

**Additional context**
Happened during a PD, after the fix you did for the game to not count as a kill, titans that you would kill out of PD. Maybe it is related to this.

**Comment by DrewBokman** [comment]
Yeah this is a weird bug, and hard to identify. Its weird that kills dont do the same thing, because they are managed in the exact same way. I will investigate further.

**Comment by DrewBokman** [comment]
fixed
