### ISSUE TITLE
Constant PD Zones

### ISSUE THREAD

**Issue by ManzWithMotto** [DrewBokman/AOTG-Public-Issue-Board#25]
Constant PD zones are good and all, but it would be much better if when your in the main menu or in game there is something that pops up telling you its a Constant PD zone, and just a continue button and a cancel one to either go or not go. The reason is accidental clicking then we have to wait 20 minutes just to leave

**Comment by j9cks** [comment]
when you click on any map from the main menu there is literally a confirm button and a back button

**Comment by ManzWithMotto** [comment]
> when you click on any map from the main menu there is literally a confirm button and a back button

I mean for PD zones, like when your in game and press tab sometimes you can accidently click a PD zone then you sit there for 20 minutes would be better if there was another confirm button for constant PD zones or some kinda warning

**Comment by Isushumi** [comment]
Yeah I can probably add an extra text on constant PD zones telling ppl its a thing
