### ISSUE TITLE
shooting someone's musket and gear kills them

### ISSUE THREAD

**Issue by j9cks** [DrewBokman/AOTG-Public-Issue-Board#27]
**Describe the bug**
someone's musket and gear counts as part of their hitbox so when you shoot it they die

**To Reproduce**
1. shoot their musket or gear

**Expected behavior**
for them to not die idk

**Screenshots**
https://medal.tv/clips/53531061/d1337ryzc7ag

**Additional context**

**Comment by DrewBokman** [comment]
fixed
