### ISSUE TITLE
New District ideas

### ISSUE THREAD

**Issue by maq119** [DrewBokman/AOTG-Public-Issue-Board#28]
**Is your feature request related to a problem? Please describe.**
No the feature request is related to creating new districts such as Orvud, Karanes, Utopia, Mitras, quinta, ect (these are just some I googled).

**Describe the solution you'd like**
I would like for new districts to be crested other than the standard Stohess, Trost and Shiganshina maps, I think it would be interesting to have unique maps. 

**Additional context**
By adding new maps such as Quinta (A district on WM) or  Yarckel (A district in WS) it will open up possibilities for lore. Maybe instead of Shiganshina being breached Quinta is, or maybe if wall maria is breached Quinta gets cut of and needs to be rescued. These are just examples of possible districts and they all open up countless possibilities to make AoT:G even more unique from other AoT games.

**Comment by Isushumi** [comment]
I already have some districts planned that lore team wants, such as underground for example
