### ISSUE TITLE
Longer charge time instead of napes being 2 hit

### ISSUE THREAD

**Issue by 3meraldzz** [DrewBokman/AOTG-Public-Issue-Board#31]
**Is your feature request related to a problem? Please describe.**
It gets really annoying sometimes when the nape is now 2 hit and you have a fully charged blade, you'd have to constantly go for the nape risking your life if its only you or another person because of the insane amount of health titans have now.

**Describe the solution you'd like**
Instead of having to hit the nape twice with 2 fully charged attacks, you could just make it so its back to being only 1 hit, but you have to charge for longer (EX: 5 seconds or more). This would be alot more reliable in stressful situations as you could kill titans faster instead of something like shiganshina breach happening again because you can't kill a titan fast enough because of its health. I know you want everyone to have to be a team to kill a titan but sometimes this just gets out of hand with hordes of titans and everyone dying in PD's because of it, not being able to kill atleast one fast enough.

**Describe alternatives you've considered**
If you really don't wanna do this then maybe you could go back to when they were killable with no charge with the instant hit registration and try to find a solution to the no charge bug.

**Additional context**
n/a

**Comment by DrewBokman** [comment]
mm i might do something like charging in combination with momentum damage, but im not sure yet

**Comment by Isushumi** [comment]
> mm i might do something like charging in combination with momentum damage, but im not sure yet

Thatd be interesting, maybe split the damage with both. if you dont have enough momentum you do half dmg, and if you dont charge long enough you dont do enough dmg either, needing to charge long enough and go fast enough to one shot
