### ISSUE TITLE
[SUGGESTION] Make shiganshina more destroyed

### ISSUE THREAD

**Issue by Roderinian** [DrewBokman/AOTG-Public-Issue-Board#32]
**Is your feature request related to a problem? Please describe.**
It is related to the problem that during the evacuation of Shiganshina titans would have smashed the place to a living hell, no way there are that many buildings left over.

**Describe the solution you'd like**
I would like for it to be more destroyed, like sure leave the HQ and shit since realistically those would have been built first but let us do a build PD for basically the rest of the district.

**Describe alternatives you've considered**
A alternative I have considered is leave like half the district good half the district destroyed.

**Additional context**
this would just be a fun PD and see the team work of all 3 branches as stated before since they stated that we would focus rebuilding the interior of Shiganshina but with this many buildings not destroyed there is no point in a build PD

**Comment by Isushumi** [comment]
I wanted to get the new shig map out asap because the old one was absolutely terrible in terms of design and performance and I wasn't going to spend another day with it.  And this is a lore suggestion anyway Idek why you're bringing that up here.
