### ISSUE TITLE
[BUG] Uniform Table in Shiganshina HQ

### ISSUE THREAD

**Issue by Max-023** [DrewBokman/AOTG-Public-Issue-Board#33]
**Describe the bug**
The uniform table in the Shiganshina HQ no work.

**To Reproduce**
1. Go to the table on the second floor.
2. Try to use it.
3. Hold F but no pop up.

**Expected behavior**
Obviously it's supposed to work as intended.

**Screenshots**
Not sure how to put up a screenshot for this.

**Additional context**
The F interact does not have the blue circle.

**Comment by DrewBokman** [comment]
fixed
