### ISSUE TITLE
Firearms do not work

### ISSUE THREAD

**Issue by ARandomDude0nGitHub** [DrewBokman/AOTG-Public-Issue-Board#35]
**Describe the bug**

**To Reproduce**
1. Take a musket/flintlock.
2. Left click w/ one of the 2
3. Musket: Can not equip, Flintlock: Will not fire. 

**Expected behavior**
To be able to take them out and fire.

**Screenshots**
https://cdn.discordapp.com/attachments/765984632637227029/849553460143325214/Roblox_2021-06-02_02-40-31.mp4
Open in discord

**Additional context**

**Comment by DrewBokman** [comment]
i fixed it last night when drip first sent me that video
