### ISSUE TITLE
Jumping cooldown

### ISSUE THREAD

**Issue by nara1-sissy** [DrewBokman/AOTG-Public-Issue-Board#38]
**Is your feature request related to a problem? Please describe.**
I hate seeing the combat system ruined by apes that spam jumps randomly to dodge projectiles, it makes trainings (and also PDs) really boring and long. It also doesn't make any sense in terms of realism since in real life when someone shoots you don't see peole running away and jumping like a basketball player, making also coverings almost completely useless

**The solution:**
I think a jump cooldown of 0.5/1 seconds would be appropriate because it also gives the occasion for shooting

**Alternatives:**
An alternative should also be that when you jump alot your jump height decreases

**Comment by DrewBokman** [comment]
added
