### ISSUE TITLE
[BUG] can't interact with HQ doors at shiganshina or trost

### ISSUE THREAD

**Issue by MetalKnightX** [DrewBokman/AOTG-Public-Issue-Board#39]
**Describe the bug**
Basically, i am at SL, (i left the TC group as well so it can't be because not having the right rank) and whenever I try to open the doors from any of these 2 places, they just won't let me interact with them.

**To Reproduce**
1. Go to Shiganshina or Trost
2. Try to interact with the doors at HQ
3. They won't move

**Expected behavior**
well, I expected them to move

**Screenshots**
Trost- https://medal.tv/clips/54372152/d1337UdiK1e7
Shig - https://medal.tv/clips/54373866/d1337seo1SNk 

**Additional context**
I was going to patrol with a friend, but when we tried to exit the HQ, neither of us could interact with the doors.

**Comment by DrewBokman** [comment]
fixed
