### ISSUE TITLE
[BUG] Training muskets do damage

### ISSUE THREAD

**Issue by zjovy** [DrewBokman/AOTG-Public-Issue-Board#42]
**Description:**
The training muskets in TC do damage just like the normal muskets. Cadets have access to them (not the cabin), and they still reload very fast.

**Steps to reproduce the behavior:**
1. Grab a training musket
2. Shoot someone or a horse

**Expected behavior:**
The training musket shouldn't do damage like how it is before, so shooting someone with it wouldn't kill them.

**Clip:**
https://medal.tv/clips/54550722/d1337LeFcDxi

**Comment by DrewBokman** [comment]
fixed
