### ISSUE TITLE
[BUG] Blind cancels

### ISSUE THREAD

**Issue by zjovy** [DrewBokman/AOTG-Public-Issue-Board#43]
**Description:** 
When a titan gets blinded twice, which means that someone blinds it again after I blinded it already, it gets unblinded.

**Steps to reproduce the behavior:**
1. Grab a buddy
2. Go to Wall Maria
3. Engage a titan by blinding it
4. Have your buddy behind you and blind it right after you do
5. The titan will be unblinded and grab you
6. No void for you because Lore Team isn't there 🤷 

**Expected behavior:**
The titan shouldn't be unblinded (at least to my knowledge, no one said this was intentional), and titan should still be blinded after the second person hits it. 

**Clip:**
https://medal.tv/clips/54425574/d1337SPtCm5u

**Comment by DrewBokman** [comment]
fixed
