### ISSUE TITLE
[BUG] Flares only show up when you have a flare in your inventory

### ISSUE THREAD

**Issue by zjovy** [DrewBokman/AOTG-Public-Issue-Board#46]
**Describe the bug**
You can only see flares when you have a flare in your toolbar. 

**To Reproduce**
1. Don't grab a flair
2. Have someone shoot a flair
3. You can't see it
4. Grab a flair
5. Have them shoot again
6. Now you can see it

**Expected behavior**
We should be able to see the flair no matter what.

**Clip**
https://medal.tv/clips/55772106/d13373rLVLnz

**Additional context**
Welcome back Drew :)

**Comment by DrewBokman** [comment]
fixed
