### ISSUE TITLE
Error Labels & Training Muskets [BUG]

### ISSUE THREAD

**Issue by EternalImperium** [DrewBokman/AOTG-Public-Issue-Board#48]
**Describe the bug**

Error Labels-
You cannot view the ranks of individuals though you can see their username and lore name. 

Training Muskets-
Training Muskets act like regular muskets regarding damage when firing, I do not believe the bayonets do damage though.

**To Reproduce**
Error Labels- Hover over the name of someone
Training Muskets- Feel free to shoot someone.

**Expected behavior**
Labels are expected to show the branch rank of the individual instead of error.
Training Muskets are expected to be harmless.

**Screenshots**

**Additional context**

**Comment by DrewBokman** [comment]
fixed
