### ISSUE TITLE
Suggestion: Law, Government, and Ministries.

### ISSUE THREAD

**Issue by fynnconstantine** [DrewBokman/AOTG-Public-Issue-Board#49]
Suggestion by: Fynn_Constantine | Fynn#6729, RG/MP

**Is your feature request related to a problem? Please describe.**

Well, this feature request doesn't come from a "problem" but rather a concern about the Civilian Life Update and the integration of the Royal Government into the game. Being in the Government group since it began, i've noticed that we have almost no integration to the admin, lore, or dev team, despite being initially organized into two ministries: the Ministry of Justice (MOJA) and the Ministry of Interal Affairs (MOIP, now called Public Affairs = MOPA)

Since the economy is coming out soon, i wanted to make this suggestion to make sure that we have integration between game mechanics and the Government, who would act as an administrator of public affairs and Justice system. (Feel free to DM me about it).

**Describe the solution you'd like**

I do not have any context on what the Civ Life Update has planned for the economy or the in-game society, but i wanted to suggest three major things:
-A banking / economy ministry and tax collection system (basically an economy)
-Integrating the Justice System that the government group is working hard on, with lots of unique legislation, with the game's jail system
-A law university for those who wish to join the MOJA

**Describe alternatives you've considered**

First one is self-explainatory; if we have a ministry of public affairs (involving economy) then we should have a system where the members of the ministry would be able to set tax rates (automatically deduced off salary), buy supplies, distribute them through the branches, make accounts of stockpiles, ETC.

Second one, i also do not know how the new jail system is going to work, but we've written lots of documents making a very efficient and unique justice system where we have court-case requests, trial procedures, attorney and prosecution boards, a hierarchy, etc. If we could have a system where players who are arrested during PD are automatically given a "Pending Trial" status, and scheduled those trials accordingly, we'd be able to judge every case uniquely, efficiently and adding a lot to the game's quality and lore. Again, DM me for any questions on that matter.

Third one: mostly for flavor. Not necessary, but i heard it was a feature being implemented with the Civ Life Update. If the government group could dialogue with the proposal and help organize things, that'd be awesome.

**Additional context**
By "lack of integration with the admin / lore / dev team" i mean we had very little contact and our organization was not directed or subject to the oversight of said teams, which could step in to help us organize things and implement this government feature into the game.
I believe this is all. Thank you very much.

-Fynn <3

**Comment by Isushumi** [comment]
Lore issue, not deving
