### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wad2k** [DrewBokman/AOTG-Public-Issue-Board#50]
**Describe the bug**
Being able to shoot yourself with musket/flint.

**To Reproduce**
Shoot a musket/flint while walking forward.

**Expected behavior**
You will die to your own bullet.

**Screenshots**
https://streamable.com/00tl91
https://streamable.com/1hgywx
https://streamable.com/x8rm8n
https://cdn.discordapp.com/attachments/783372649262481431/856653991868628992/MedalTVRoblox20210621174217_Trim.mp4

**Additional context**
Happens almost every interior pd, is annoying for both LT and MP/SG to deal with.

**Comment by DrewBokman** [comment]
fixed
