### ISSUE TITLE
Cannon choppiness and animations don't work for like 10+ mins

### ISSUE THREAD

**Issue by Ozzekqel** [DrewBokman/AOTG-Public-Issue-Board#52]
**Describe the bug**
The cannons will be very choppy and the cannon won't extend with R, no animations either. Just randomly solves itself after you sit on a cannon for around 20 mins

**To Reproduce**
1. Go to Shig and grab gear
2. Sit on a cannon, its probably gonna be choppy and you'll just be in a frozen walking animation on the seat
3. Shoot it for a couple of minutes
4. Animations and R extend now works, proper animations are in, and WASD is more smooth

**Expected behavior**
For the cannons to be smooth from the beginning 

**Screenshots**
Before: https://prnt.sc/16eal2y
After: https://prnt.sc/16eapt2

**Comment by DrewBokman** [comment]
fixed with recent cannon improvements
