### ISSUE TITLE
Unable to pick up medbag

### ISSUE THREAD

**Issue by iRoyce** [DrewBokman/AOTG-Public-Issue-Board#64]
**Is your feature request related to a problem? Please describe.**
In the Patreon place, you're unable to pick up the medical bag.

**Describe the solution you'd like**
To be able to pick it up so we can try it out.

**Describe alternatives you've considered**
If there's a whitelist for certain people to use it right now, open it up to everyone for testing.

**Additional context**
Basically to replicate it, team yourself scout (that's my team rn), head up to the med box, then press F. Nothing will happen.

**Comment by DrewBokman** [comment]
you need to be whitelisted
