### ISSUE TITLE
Titans popping out of nowhere, adding footstep sounds to titans.

### ISSUE THREAD

**Issue by clumsyfeelings** [DrewBokman/AOTG-Public-Issue-Board#8]
**Is your feature request related to a problem? Please describe.**
Yes, this has happened to multiple SL/SG. Titans in the fog hidden popping out of nowhere, with no signs or hints. Many people have died to this recently, especially offensive squads in the branches that engage the titans and are off the walls 24/7.

**Describe the solution you'd like**
Add footstep sounds to the titans. This will make it much more easier on branch members, and make the game more realistic as a whole. Titans are massive, hearing their loud footsteps can assist branch members and their situational awareness. The fog is really thick, and titans popping out of nowhere with no hints is really unfair in my opinion, the best we can have for this is hearing titans and where they're coming from, so we can actually do something instead of recklessly charging.

**Describe alternatives you've considered**
I don't know any alternatives for this, I guess just lower the density of fog but I don't believe that's happening. You guys can even add titan footmarks on the snow when they take each step. 

**Additional context**
https://streamable.com/bawwav
https://cdn.discordapp.com/attachments/822823821937606678/842384938866966568/video0.mov
https://cdn.discordapp.com/attachments/822823821937606678/842535038637178890/video0_2.mp4

**Comment by SharkSnake64** [comment]
this would save a ton of lives in the state we are in rn..

**Comment by clumsyfeelings** [comment]
Seriously, we don't have a single clue of which direction titans will be coming from.

**Comment by Isushumi** [comment]
Ok, yes increasing the sounds of titans walking can and will be done. But this issue seems like it stems more from the fact that you lack situational awareness, the point of the fog is to lower that exact sense. We're not gonna keep giving you guys stuff on a silver platter, you will need to adapt to your situations whether you like it or not.

**Comment by DrewBokman** [comment]
Titans do have pretty loud footsteps, in fact I personally can hear then across the whole map. But I think they ususally get drowned out by music and comms. Sooo

**Comment by DrewBokman** [comment]
@Isushumi increase the volume of the footsteps and then close this issue.

**Comment by Isushumi** [comment]
Done btw
